package config

import (
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

// Saver handles configuration persistence
type Saver struct{}

// NewSaver creates a new configuration saver
func NewSaver() *Saver {
	return &Saver{}
}

// SaveGlobalConfig writes configuration to ~/.gendocs.yaml
func (s *Saver) SaveGlobalConfig(cfg *GlobalConfig) error {
	path, err := GlobalConfigPath()
	if err != nil {
		return fmt.Errorf("failed to get global config path: %w", err)
	}
	return s.saveToPath(path, cfg)
}

// SaveProjectConfig writes configuration to .ai/config.yaml
func (s *Saver) SaveProjectConfig(repoPath string, cfg *GlobalConfig) error {
	if repoPath == "" {
		repoPath = "."
	}
	path := filepath.Join(repoPath, ".ai", "config.yaml")
	return s.saveToPath(path, cfg)
}

// saveToPath serializes and writes config with proper permissions
func (s *Saver) saveToPath(path string, cfg *GlobalConfig) error {
	// Ensure version is set
	if cfg.Version == 0 {
		cfg.Version = CurrentConfigVersion
	}

	data, err := yaml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("failed to marshal config: %w", err)
	}

	// Add header comment
	header := "# Gendocs Configuration\n# Generated by gendocs config dashboard\n# For documentation, see: https://github.com/user/gendocs\n\n"
	fullContent := []byte(header + string(data))

	// Ensure directory exists
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}

	// Write with secure permissions (0600 for API keys)
	if err := os.WriteFile(path, fullContent, 0600); err != nil {
		return fmt.Errorf("failed to write config file: %w", err)
	}

	return nil
}

// GlobalConfigPath returns ~/.gendocs.yaml path
func GlobalConfigPath() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("failed to get user home directory: %w", err)
	}
	return filepath.Join(home, ".gendocs.yaml"), nil
}

// ProjectConfigPath returns .ai/config.yaml path for a given repo
func ProjectConfigPath(repoPath string) string {
	if repoPath == "" {
		repoPath = "."
	}
	return filepath.Join(repoPath, ".ai", "config.yaml")
}

// ConfigExists checks if a config file exists at the given path
func ConfigExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

// GlobalConfigExists checks if ~/.gendocs.yaml exists
func GlobalConfigExists() bool {
	path, err := GlobalConfigPath()
	if err != nil {
		return false
	}
	return ConfigExists(path)
}

// ProjectConfigExists checks if .ai/config.yaml exists in the repo
func ProjectConfigExists(repoPath string) bool {
	return ConfigExists(ProjectConfigPath(repoPath))
}
